export const GET_SPECIALIES = "GET_SPECIALIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_LEVELS = "GET_LEVELS";
export const GET_SPECIALIESWITHLEVEL="GET_SPECIALIESWITHLEVEL";

